script: |
  cd ~/hate-speech-project
  git pull origin main
  
  # stop old app
  pkill -f app.py || true
  
  # install dependencies (safe)
  pip3 install -r requirements.txt --break-system-packages
  
  # start app again
  nohup python3 app/app.py > log.txt 2>&1 &
